module RbsDraper
  module Decoratable
    def self.all: () -> Array[singleton(Draper::Decoratable)]
    def self.class_to_rbs: (singleton(Draper::Decoratable) klass) -> String

    class Generator
      attr_reader klass: singleton(Draper::Decoratable)
      attr_reader klass_name: String

      def initialize: (singleton(Draper::Decoratable) klass) -> void
      def generate: () -> String

      private

      def format: (String rbs) -> String
      def header: () -> String
      def method_decls: () -> String
      def footer: () -> String
      def module_names: () -> Array[String]
    end
  end
end
