module RbsDraper
  module Decorator
    def self.class_to_rbs: (singleton(Draper::Decorator) klass, RBS::DefinitionBuilder rbs_builder, ?decorated_class: singleton(Class)?) -> String?

    class Generator
      attr_reader klass: singleton(Draper::Decorator)
      attr_reader klass_name: String
      attr_reader rbs_builder: RBS::DefinitionBuilder
      attr_reader decorated_class: singleton(Class)?

      @decorated_class_def: RBS::Definition
      @user_defined_class: RBS::Definition

      def initialize: (singleton(Draper::Decorator) klass, RBS::DefinitionBuilder rbs_builder, ?decorated_class: singleton(Class)?) -> void
      def generate: () -> String?

      private

      def klass_decl: () -> String
      def header: () -> String
      def object_method_decls: () -> String
      def method_decls: () -> String?
      def footer: () -> String
      def module_names: () -> Array[String]
      def decorated_class_def: () -> RBS::Definition?
      def delegated_methods: () -> Array[[Symbol, RBS::Definition::Method]]
      def user_defined_class: () -> RBS::Definition?
    end
  end
end
