AllCops:
  TargetRubyVersion: 3.2

plugins:
  - rubocop-numbered-params
  - rubocop-rake
  - rubocop-rbs_inline

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Style/Documentation:
  Enabled: false

Style/RbsInline/MissingTypeAnnotation:
  EnforcedStyle: doc_style_and_return_annotation

Style/RbsInline/RedundantTypeAnnotation:
  EnforcedStyle: doc_style_and_return_annotation

Style/RbsInline/RequireRbsInlineComment:
  EnforcedStyle: never

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 20
